ak3/backend: Check ROM target level before installing
Yes, you can patch cmdline to get 4.9 kernel to boot on 3.18-compiled ROM,
but RIP video playback. I'm serious.

Signed-off-by: Albert I <kras@raphielgang.org>

diff --git a/META-INF/com/google/android/update-binary b/META-INF/com/google/android/update-binary
--- a/META-INF/com/google/android/update-binary
+++ b/META-INF/com/google/android/update-binary
@@ -423,6 +423,10 @@ do_levelcheck;
 if [ "$(file_getprop /system/build.prop ro.treble.enabled)" != "true" ]; then
   abort "Non-treble ROMs are unsupported. Aborting...";
 fi
+[ "$ZIPFILE" =~ "legacy" ] && target_lvl=2 || target_lvl=3
+if ! grep -q "target-level=\"$target_lvl\"" /vendor/etc/vintf/manifest.xml; then
+  abort "Unsupported ROM and kernel combo detected. Aborting..."
+fi
 
 ui_print "Installing...";
 CORE=$($BB grep -oE 'ak.*core.sh' anykernel.sh);
